### ISSUE TITLE
Add dependencies to README

### ISSUE THREAD

**Issue by mogren-usds** [sverch/ansible-harness#1]
Add all of the dependencies to a section in the README:
- Virtualbox
- etc.

**Comment by sverchdotgov** [comment]
Thanks for the issue @mogrenAtWork!  Done here: https://github.com/sverch/ansible-harness/commit/85080e55b866fdae258af3c7144cd486b0f016a9.

Eventually once there are multiple backends supported and not just Virtualbox there will be more dependencies (like the AWS sdk).

**Comment by sverch** [comment]
Thanks for the issue @mogrenAtWork!  Fixed here: https://github.com/sverch/ansible-harness/commit/85080e55b866fdae258af3c7144cd486b0f016a9.

Eventually there may be more dependencies once AWS support is added.
